/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace BlackScholes {
  export type BlackScholesInputsStruct = {
    timeToExpirySec: BigNumberish;
    volatilityDecimal: BigNumberish;
    spotDecimal: BigNumberish;
    strikePriceDecimal: BigNumberish;
    rateDecimal: BigNumberish;
  };

  export type BlackScholesInputsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    timeToExpirySec: BigNumber;
    volatilityDecimal: BigNumber;
    spotDecimal: BigNumber;
    strikePriceDecimal: BigNumber;
    rateDecimal: BigNumber;
  };

  export type PricesDeltaStdVegaStruct = {
    callPrice: BigNumberish;
    putPrice: BigNumberish;
    callDelta: BigNumberish;
    putDelta: BigNumberish;
    stdVega: BigNumberish;
  };

  export type PricesDeltaStdVegaStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    callPrice: BigNumber;
    putPrice: BigNumber;
    callDelta: BigNumber;
    putDelta: BigNumber;
    stdVega: BigNumber;
  };

  export type PricesDeltaVegaStruct = {
    callPrice: BigNumberish;
    putPrice: BigNumberish;
    callDelta: BigNumberish;
    putDelta: BigNumberish;
    vega: BigNumberish;
  };

  export type PricesDeltaVegaStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    callPrice: BigNumber;
    putPrice: BigNumber;
    callDelta: BigNumber;
    putDelta: BigNumber;
    vega: BigNumber;
  };
}

export interface BlackScholesInterface extends utils.Interface {
  contractName: "BlackScholes";
  functions: {
    "delta((uint256,uint256,uint256,uint256,int256))": FunctionFragment;
    "optionPrices((uint256,uint256,uint256,uint256,int256))": FunctionFragment;
    "pricesDeltaStdVega((uint256,uint256,uint256,uint256,int256))": FunctionFragment;
    "pricesDeltaVega((uint256,uint256,uint256,uint256,int256))": FunctionFragment;
    "vega((uint256,uint256,uint256,uint256,int256))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "delta",
    values: [BlackScholes.BlackScholesInputsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "optionPrices",
    values: [BlackScholes.BlackScholesInputsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "pricesDeltaStdVega",
    values: [BlackScholes.BlackScholesInputsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "pricesDeltaVega",
    values: [BlackScholes.BlackScholesInputsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "vega",
    values: [BlackScholes.BlackScholesInputsStruct]
  ): string;

  decodeFunctionResult(functionFragment: "delta", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "optionPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricesDeltaStdVega",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricesDeltaVega",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vega", data: BytesLike): Result;

  events: {};
}

export interface BlackScholes extends BaseContract {
  contractName: "BlackScholes";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BlackScholesInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    delta(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        callDeltaDecimal: BigNumber;
        putDeltaDecimal: BigNumber;
      }
    >;

    optionPrices(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>;

    pricesDeltaStdVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<[BlackScholes.PricesDeltaStdVegaStructOutput]>;

    pricesDeltaVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<[BlackScholes.PricesDeltaVegaStructOutput]>;

    vega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { vegaDecimal: BigNumber }>;
  };

  delta(
    bsInput: BlackScholes.BlackScholesInputsStruct,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      callDeltaDecimal: BigNumber;
      putDeltaDecimal: BigNumber;
    }
  >;

  optionPrices(
    bsInput: BlackScholes.BlackScholesInputsStruct,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>;

  pricesDeltaStdVega(
    bsInput: BlackScholes.BlackScholesInputsStruct,
    overrides?: CallOverrides
  ): Promise<BlackScholes.PricesDeltaStdVegaStructOutput>;

  pricesDeltaVega(
    bsInput: BlackScholes.BlackScholesInputsStruct,
    overrides?: CallOverrides
  ): Promise<BlackScholes.PricesDeltaVegaStructOutput>;

  vega(
    bsInput: BlackScholes.BlackScholesInputsStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    delta(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        callDeltaDecimal: BigNumber;
        putDeltaDecimal: BigNumber;
      }
    >;

    optionPrices(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { call: BigNumber; put: BigNumber }>;

    pricesDeltaStdVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BlackScholes.PricesDeltaStdVegaStructOutput>;

    pricesDeltaVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BlackScholes.PricesDeltaVegaStructOutput>;

    vega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    delta(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    optionPrices(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pricesDeltaStdVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pricesDeltaVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    delta(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    optionPrices(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pricesDeltaStdVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pricesDeltaVega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vega(
      bsInput: BlackScholes.BlackScholesInputsStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
