/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace OptionMarketPricer {
  export type PricingParametersStruct = {
    optionPriceFeeCoefficient: BigNumberish;
    optionPriceFee1xPoint: BigNumberish;
    optionPriceFee2xPoint: BigNumberish;
    spotPriceFeeCoefficient: BigNumberish;
    spotPriceFee1xPoint: BigNumberish;
    spotPriceFee2xPoint: BigNumberish;
    vegaFeeCoefficient: BigNumberish;
    standardSize: BigNumberish;
    skewAdjustmentFactor: BigNumberish;
  };

  export type PricingParametersStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    optionPriceFeeCoefficient: BigNumber;
    optionPriceFee1xPoint: BigNumber;
    optionPriceFee2xPoint: BigNumber;
    spotPriceFeeCoefficient: BigNumber;
    spotPriceFee1xPoint: BigNumber;
    spotPriceFee2xPoint: BigNumber;
    vegaFeeCoefficient: BigNumber;
    standardSize: BigNumber;
    skewAdjustmentFactor: BigNumber;
  };

  export type TradeLimitParametersStruct = {
    minDelta: BigNumberish;
    minForceCloseDelta: BigNumberish;
    tradingCutoff: BigNumberish;
    minBaseIV: BigNumberish;
    maxBaseIV: BigNumberish;
    minSkew: BigNumberish;
    maxSkew: BigNumberish;
    minVol: BigNumberish;
    maxVol: BigNumberish;
    absMinSkew: BigNumberish;
    absMaxSkew: BigNumberish;
  };

  export type TradeLimitParametersStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    minDelta: BigNumber;
    minForceCloseDelta: BigNumber;
    tradingCutoff: BigNumber;
    minBaseIV: BigNumber;
    maxBaseIV: BigNumber;
    minSkew: BigNumber;
    maxSkew: BigNumber;
    minVol: BigNumber;
    maxVol: BigNumber;
    absMinSkew: BigNumber;
    absMaxSkew: BigNumber;
  };

  export type TradeResultStruct = {
    premium: BigNumberish;
    optionPriceFee: BigNumberish;
    spotPriceFee: BigNumberish;
    vegaUtilFee: BigNumberish;
    totalCost: BigNumberish;
    volTraded: BigNumberish;
    newBaseIv: BigNumberish;
    newSkew: BigNumberish;
  };

  export type TradeResultStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    premium: BigNumber;
    optionPriceFee: BigNumber;
    spotPriceFee: BigNumber;
    vegaUtilFee: BigNumber;
    totalCost: BigNumber;
    volTraded: BigNumber;
    newBaseIv: BigNumber;
    newSkew: BigNumber;
  };
}

export declare namespace LiquidityPool {
  export type LiquidityStruct = {
    freeLiquidity: BigNumberish;
    burnableLiquidity: BigNumberish;
    usedCollatLiquidity: BigNumberish;
    pendingDeltaLiquidity: BigNumberish;
    usedDeltaLiquidity: BigNumberish;
    NAV: BigNumberish;
  };

  export type LiquidityStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    freeLiquidity: BigNumber;
    burnableLiquidity: BigNumber;
    usedCollatLiquidity: BigNumber;
    pendingDeltaLiquidity: BigNumber;
    usedDeltaLiquidity: BigNumber;
    NAV: BigNumber;
  };
}

export declare namespace SynthetixAdapter {
  export type ExchangeParamsStruct = {
    spotPrice: BigNumberish;
    quoteKey: BytesLike;
    baseKey: BytesLike;
    short: string;
    quoteBaseFeeRate: BigNumberish;
    baseQuoteFeeRate: BigNumberish;
  };

  export type ExchangeParamsStructOutput = [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber
  ] & {
    spotPrice: BigNumber;
    quoteKey: string;
    baseKey: string;
    short: string;
    quoteBaseFeeRate: BigNumber;
    baseQuoteFeeRate: BigNumber;
  };
}

export declare namespace OptionMarket {
  export type TradeStruct = {
    isBuy: boolean;
    isForceClose: boolean;
    tradeDirection: BigNumberish;
    optionType: BigNumberish;
    amount: BigNumberish;
    expiry: BigNumberish;
    strikePrice: BigNumberish;
    liquidity: LiquidityPool.LiquidityStruct;
    exchangeParams: SynthetixAdapter.ExchangeParamsStruct;
  };

  export type TradeStructOutput = [
    boolean,
    boolean,
    number,
    number,
    BigNumber,
    BigNumber,
    BigNumber,
    LiquidityPool.LiquidityStructOutput,
    SynthetixAdapter.ExchangeParamsStructOutput
  ] & {
    isBuy: boolean;
    isForceClose: boolean;
    tradeDirection: number;
    optionType: number;
    amount: BigNumber;
    expiry: BigNumber;
    strikePrice: BigNumber;
    liquidity: LiquidityPool.LiquidityStructOutput;
    exchangeParams: SynthetixAdapter.ExchangeParamsStructOutput;
  };

  export type StrikeStruct = {
    id: BigNumberish;
    strikePrice: BigNumberish;
    skew: BigNumberish;
    longCall: BigNumberish;
    shortCallBase: BigNumberish;
    shortCallQuote: BigNumberish;
    longPut: BigNumberish;
    shortPut: BigNumberish;
    boardId: BigNumberish;
  };

  export type StrikeStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    id: BigNumber;
    strikePrice: BigNumber;
    skew: BigNumber;
    longCall: BigNumber;
    shortCallBase: BigNumber;
    shortCallQuote: BigNumber;
    longPut: BigNumber;
    shortPut: BigNumber;
    boardId: BigNumber;
  };
}

export declare namespace OptionGreekCache {
  export type TradePricingStruct = {
    optionPrice: BigNumberish;
    preTradeAmmNetStdVega: BigNumberish;
    postTradeAmmNetStdVega: BigNumberish;
    callDelta: BigNumberish;
    volTraded: BigNumberish;
  };

  export type TradePricingStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    optionPrice: BigNumber;
    preTradeAmmNetStdVega: BigNumber;
    postTradeAmmNetStdVega: BigNumber;
    callDelta: BigNumber;
    volTraded: BigNumber;
  };
}

export interface OptionMarketPricerInterface extends utils.Interface {
  contractName: "OptionMarketPricer";
  functions: {
    "getPricingParams()": FunctionFragment;
    "getTimeWeightedFee(uint256,uint256,uint256,uint256)": FunctionFragment;
    "getTradeLimitParams()": FunctionFragment;
    "getTradeResult((bool,bool,uint8,uint8,uint256,uint256,uint256,(uint256,uint256,uint256,uint256,uint256,uint256),(uint256,bytes32,bytes32,address,uint256,uint256)),(uint256,int256,int256,int256,uint256),uint256,uint256)": FunctionFragment;
    "getVegaUtilFee((bool,bool,uint8,uint8,uint256,uint256,uint256,(uint256,uint256,uint256,uint256,uint256,uint256),(uint256,bytes32,bytes32,address,uint256,uint256)),(uint256,int256,int256,int256,uint256))": FunctionFragment;
    "init(address,address)": FunctionFragment;
    "ivImpactForTrade((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256),(bool,bool,uint8,uint8,uint256,uint256,uint256,(uint256,uint256,uint256,uint256,uint256,uint256),(uint256,bytes32,bytes32,address,uint256,uint256)),uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "pricingParams()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setPricingParams((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "setTradeLimitParams((int256,int256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
    "tradeLimitParams()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateCacheAndGetTradeResult((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256),(bool,bool,uint8,uint8,uint256,uint256,uint256,(uint256,uint256,uint256,uint256,uint256,uint256),(uint256,bytes32,bytes32,address,uint256,uint256)),uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getPricingParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTimeWeightedFee",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeLimitParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTradeResult",
    values: [
      OptionMarket.TradeStruct,
      OptionGreekCache.TradePricingStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getVegaUtilFee",
    values: [OptionMarket.TradeStruct, OptionGreekCache.TradePricingStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "ivImpactForTrade",
    values: [OptionMarket.StrikeStruct, OptionMarket.TradeStruct, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pricingParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPricingParams",
    values: [OptionMarketPricer.PricingParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradeLimitParams",
    values: [OptionMarketPricer.TradeLimitParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "tradeLimitParams",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateCacheAndGetTradeResult",
    values: [
      OptionMarket.StrikeStruct,
      OptionMarket.TradeStruct,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getPricingParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTimeWeightedFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeLimitParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTradeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVegaUtilFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ivImpactForTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pricingParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPricingParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradeLimitParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradeLimitParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCacheAndGetTradeResult",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "PricingParametersSet(tuple)": EventFragment;
    "TradeLimitParametersSet(tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PricingParametersSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TradeLimitParametersSet"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export type PricingParametersSetEvent = TypedEvent<
  [OptionMarketPricer.PricingParametersStructOutput],
  { pricingParams: OptionMarketPricer.PricingParametersStructOutput }
>;

export type PricingParametersSetEventFilter =
  TypedEventFilter<PricingParametersSetEvent>;

export type TradeLimitParametersSetEvent = TypedEvent<
  [OptionMarketPricer.TradeLimitParametersStructOutput],
  { tradeLimitParams: OptionMarketPricer.TradeLimitParametersStructOutput }
>;

export type TradeLimitParametersSetEventFilter =
  TypedEventFilter<TradeLimitParametersSetEvent>;

export interface OptionMarketPricer extends BaseContract {
  contractName: "OptionMarketPricer";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OptionMarketPricerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPricingParams(
      overrides?: CallOverrides
    ): Promise<[OptionMarketPricer.PricingParametersStructOutput]>;

    getTimeWeightedFee(
      expiry: BigNumberish,
      pointA: BigNumberish,
      pointB: BigNumberish,
      coefficient: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { timeWeightedFee: BigNumber }>;

    getTradeLimitParams(
      overrides?: CallOverrides
    ): Promise<[OptionMarketPricer.TradeLimitParametersStructOutput]>;

    getTradeResult(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      newBaseIv: BigNumberish,
      newSkew: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[OptionMarketPricer.TradeResultStructOutput]>;

    getVegaUtilFee(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { vegaUtilFee: BigNumber }>;

    init(
      _optionMarket: string,
      _greekCache: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ivImpactForTrade(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pricingParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        optionPriceFeeCoefficient: BigNumber;
        optionPriceFee1xPoint: BigNumber;
        optionPriceFee2xPoint: BigNumber;
        spotPriceFeeCoefficient: BigNumber;
        spotPriceFee1xPoint: BigNumber;
        spotPriceFee2xPoint: BigNumber;
        vegaFeeCoefficient: BigNumber;
        standardSize: BigNumber;
        skewAdjustmentFactor: BigNumber;
      }
    >;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPricingParams(
      _pricingParams: OptionMarketPricer.PricingParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTradeLimitParams(
      _tradeLimitParams: OptionMarketPricer.TradeLimitParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tradeLimitParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minDelta: BigNumber;
        minForceCloseDelta: BigNumber;
        tradingCutoff: BigNumber;
        minBaseIV: BigNumber;
        maxBaseIV: BigNumber;
        minSkew: BigNumber;
        maxSkew: BigNumber;
        minVol: BigNumber;
        maxVol: BigNumber;
        absMinSkew: BigNumber;
        absMaxSkew: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateCacheAndGetTradeResult(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      boardExpiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getPricingParams(
    overrides?: CallOverrides
  ): Promise<OptionMarketPricer.PricingParametersStructOutput>;

  getTimeWeightedFee(
    expiry: BigNumberish,
    pointA: BigNumberish,
    pointB: BigNumberish,
    coefficient: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTradeLimitParams(
    overrides?: CallOverrides
  ): Promise<OptionMarketPricer.TradeLimitParametersStructOutput>;

  getTradeResult(
    trade: OptionMarket.TradeStruct,
    pricing: OptionGreekCache.TradePricingStruct,
    newBaseIv: BigNumberish,
    newSkew: BigNumberish,
    overrides?: CallOverrides
  ): Promise<OptionMarketPricer.TradeResultStructOutput>;

  getVegaUtilFee(
    trade: OptionMarket.TradeStruct,
    pricing: OptionGreekCache.TradePricingStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  init(
    _optionMarket: string,
    _greekCache: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ivImpactForTrade(
    strike: OptionMarket.StrikeStruct,
    trade: OptionMarket.TradeStruct,
    boardBaseIv: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  owner(overrides?: CallOverrides): Promise<string>;

  pricingParams(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      optionPriceFeeCoefficient: BigNumber;
      optionPriceFee1xPoint: BigNumber;
      optionPriceFee2xPoint: BigNumber;
      spotPriceFeeCoefficient: BigNumber;
      spotPriceFee1xPoint: BigNumber;
      spotPriceFee2xPoint: BigNumber;
      vegaFeeCoefficient: BigNumber;
      standardSize: BigNumber;
      skewAdjustmentFactor: BigNumber;
    }
  >;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPricingParams(
    _pricingParams: OptionMarketPricer.PricingParametersStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTradeLimitParams(
    _tradeLimitParams: OptionMarketPricer.TradeLimitParametersStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tradeLimitParams(
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      minDelta: BigNumber;
      minForceCloseDelta: BigNumber;
      tradingCutoff: BigNumber;
      minBaseIV: BigNumber;
      maxBaseIV: BigNumber;
      minSkew: BigNumber;
      maxSkew: BigNumber;
      minVol: BigNumber;
      maxVol: BigNumber;
      absMinSkew: BigNumber;
      absMaxSkew: BigNumber;
    }
  >;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateCacheAndGetTradeResult(
    strike: OptionMarket.StrikeStruct,
    trade: OptionMarket.TradeStruct,
    boardBaseIv: BigNumberish,
    boardExpiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPricingParams(
      overrides?: CallOverrides
    ): Promise<OptionMarketPricer.PricingParametersStructOutput>;

    getTimeWeightedFee(
      expiry: BigNumberish,
      pointA: BigNumberish,
      pointB: BigNumberish,
      coefficient: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTradeLimitParams(
      overrides?: CallOverrides
    ): Promise<OptionMarketPricer.TradeLimitParametersStructOutput>;

    getTradeResult(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      newBaseIv: BigNumberish,
      newSkew: BigNumberish,
      overrides?: CallOverrides
    ): Promise<OptionMarketPricer.TradeResultStructOutput>;

    getVegaUtilFee(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    init(
      _optionMarket: string,
      _greekCache: string,
      overrides?: CallOverrides
    ): Promise<void>;

    ivImpactForTrade(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    owner(overrides?: CallOverrides): Promise<string>;

    pricingParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        optionPriceFeeCoefficient: BigNumber;
        optionPriceFee1xPoint: BigNumber;
        optionPriceFee2xPoint: BigNumber;
        spotPriceFeeCoefficient: BigNumber;
        spotPriceFee1xPoint: BigNumber;
        spotPriceFee2xPoint: BigNumber;
        vegaFeeCoefficient: BigNumber;
        standardSize: BigNumber;
        skewAdjustmentFactor: BigNumber;
      }
    >;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setPricingParams(
      _pricingParams: OptionMarketPricer.PricingParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    setTradeLimitParams(
      _tradeLimitParams: OptionMarketPricer.TradeLimitParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    tradeLimitParams(
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        minDelta: BigNumber;
        minForceCloseDelta: BigNumber;
        tradingCutoff: BigNumber;
        minBaseIV: BigNumber;
        maxBaseIV: BigNumber;
        minSkew: BigNumber;
        maxSkew: BigNumber;
        minVol: BigNumber;
        maxVol: BigNumber;
        absMinSkew: BigNumber;
        absMaxSkew: BigNumber;
      }
    >;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateCacheAndGetTradeResult(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      boardExpiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<OptionMarketPricer.TradeResultStructOutput>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;

    "PricingParametersSet(tuple)"(
      pricingParams?: null
    ): PricingParametersSetEventFilter;
    PricingParametersSet(pricingParams?: null): PricingParametersSetEventFilter;

    "TradeLimitParametersSet(tuple)"(
      tradeLimitParams?: null
    ): TradeLimitParametersSetEventFilter;
    TradeLimitParametersSet(
      tradeLimitParams?: null
    ): TradeLimitParametersSetEventFilter;
  };

  estimateGas: {
    getPricingParams(overrides?: CallOverrides): Promise<BigNumber>;

    getTimeWeightedFee(
      expiry: BigNumberish,
      pointA: BigNumberish,
      pointB: BigNumberish,
      coefficient: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTradeLimitParams(overrides?: CallOverrides): Promise<BigNumber>;

    getTradeResult(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      newBaseIv: BigNumberish,
      newSkew: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getVegaUtilFee(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    init(
      _optionMarket: string,
      _greekCache: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ivImpactForTrade(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pricingParams(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPricingParams(
      _pricingParams: OptionMarketPricer.PricingParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTradeLimitParams(
      _tradeLimitParams: OptionMarketPricer.TradeLimitParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tradeLimitParams(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateCacheAndGetTradeResult(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      boardExpiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPricingParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTimeWeightedFee(
      expiry: BigNumberish,
      pointA: BigNumberish,
      pointB: BigNumberish,
      coefficient: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradeLimitParams(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTradeResult(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      newBaseIv: BigNumberish,
      newSkew: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVegaUtilFee(
      trade: OptionMarket.TradeStruct,
      pricing: OptionGreekCache.TradePricingStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    init(
      _optionMarket: string,
      _greekCache: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ivImpactForTrade(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pricingParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPricingParams(
      _pricingParams: OptionMarketPricer.PricingParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTradeLimitParams(
      _tradeLimitParams: OptionMarketPricer.TradeLimitParametersStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tradeLimitParams(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateCacheAndGetTradeResult(
      strike: OptionMarket.StrikeStruct,
      trade: OptionMarket.TradeStruct,
      boardBaseIv: BigNumberish,
      boardExpiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
