/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ISupervisor, ISupervisorInterface } from "../ISupervisor";

const _abi = [
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISupervisor__factory {
  static readonly abi = _abi;
  static createInterface(): ISupervisorInterface {
    return new utils.Interface(_abi) as ISupervisorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISupervisor {
    return new Contract(address, _abi, signerOrProvider) as ISupervisor;
  }
}
